"use client";

import { useMemo, useState } from "react";

type Perspective = { key: string; name: string; color: string; description: string; question: string };
type ResearchSource = { title: string; url: string; type: "논문·학술지" | "전공 서적" | "뉴스·웹 자료"; publisher?: string };
type AiContent = { perspectives: Array<{ key: string; question: string; description: string; example: string }>; paths: Array<{ title: string; text: string; detail: string }>; basic: { what: string; how: string; discover: string }; deepening: Array<{ title: string; text: string }>; report: { title: string; intro: string; question: string; background: string; method: string }; sources?: ResearchSource[] };

const perspectives: Perspective[] = ["정의", "범위", "유사성", "위계", "변수", "조건", "수단", "예외", "사례", "모형"].map((name, index) => ({ key: ["definition", "scope", "similarity", "hierarchy", "variable", "condition", "method", "exception", "case", "model"][index], name, color: ["violet", "indigo", "blue", "teal", "amber", "orange", "green", "rose", "cyan", "purple"][index], description: `${name} 관점에서 주제를 새롭게 바라보고 탐구 질문으로 좁혀 갑니다.`, question: `${name} 관점에서 이 주제를 어떻게 파고들 수 있을까?` }));
function buildApproaches(topic: string, perspective: Perspective, generated?: AiContent["perspectives"][number]) {
  const question = generated?.question || `${topic}의 ${perspective.name}은(는) 무엇이며, 어떤 질문으로 확인할 수 있을까?`;
  return [
    { title: "1단계 심화 · 핵심을 쪼개 보기", text: `${perspective.name} 관점에서 ${topic}의 핵심 요소를 더 작은 질문으로 나누기`, detail: `${question}을 세부 질문 2~3개로 쪼개고, 각 질문에 답하기 위해 필요한 개념과 자료를 정리합니다.` },
    { title: "2단계 심화 · 조건을 바꿔 보기", text: `${perspective.name} 관점의 조건을 하나씩 바꾸며 달라지는 결과 찾기`, detail: `${topic}의 사례에서 한 가지 조건만 바꾸고, 설명이 유지되거나 어긋나는 지점을 비교표와 근거로 기록합니다.` },
    { title: "3단계 심화 · 다른 사례로 확장하기", text: `${perspective.name} 관점으로 찾은 구조를 다른 사례에도 적용해 보기`, detail: `${topic}의 핵심 구조를 다른 사례나 교과 개념에 옮겨 보고, 그대로 적용되는 부분과 새롭게 수정해야 하는 부분을 구분합니다.` },
  ];
}

function fallbackCopy(item: Perspective, topic: string) {
  const subject = topic || "이 주제";
  return { question: `${subject}의 ${item.name}은(는) 무엇이며, 어떤 질문으로 확인할 수 있을까?`, description: `${subject}을 ${item.name} 관점에서 관찰하고 근거를 모아 봅니다.`, example: `${subject}의 실제 사례를 하나 고르고, ${item.name} 관점에서 달라지는 점을 표로 정리합니다.` };
}

export default function Home() {
  const [step, setStep] = useState(1);
  const [student, setStudent] = useState({ number: "", name: "", topic: "" });
  const [selectedPerspective, setSelectedPerspective] = useState(1);
  const [selectedPath, setSelectedPath] = useState(0);
  const [ai, setAi] = useState<AiContent | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const topic = student.topic.trim() || "관심 주제";
  const selected = perspectives[selectedPerspective];
  const selectedAiPerspective = ai?.perspectives?.find((item) => item.key === selected.key);
  const approaches = buildApproaches(topic, selected, selectedAiPerspective);
  const report = useMemo(() => ai?.report || { title: `${topic} 탐구 보고서`, intro: `${topic}에 관심을 갖게 된 계기와 관찰한 현상을 정리한다.`, question: `${topic}은 어떤 조건에서 달라지는가?`, background: `${topic}의 핵심 개념과 관련 사례를 조사한다.`, method: `${topic}의 사례를 관찰하고 조건을 바꾸어 결과를 비교한다.` }, [ai, topic]);

  async function generate() {
    if (!student.topic.trim()) { setError("먼저 관심 주제를 입력해 주세요."); return; }
    setLoading(true); setError("");
    try { const response = await fetch("/api/inquiry", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ topic: student.topic }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Gemini 생성에 실패했습니다."); setAi(data); setStep(2); } catch (cause) { setError(cause instanceof Error ? cause.message : "Gemini 생성에 실패했습니다."); setAi(null); setStep(2); } finally { setLoading(false); }
  }
  function reset() { setStep(1); setStudent({ number: "", name: "", topic: "" }); setAi(null); setError(""); }

  return <main className="inquiry-app"><header className="app-header"><div className="mini-brand"><span>탐</span><div><strong>탐구 주제 찾기</strong><small>Inquiry Studio</small></div></div><div className="school-pill">고등학교 2학년 <span>⌄</span></div><button className="settings-button">⚙ Gemini API 설정</button></header><nav className="progress-nav"><button onClick={() => setStep(1)}>← 처음</button><span>학생 분석</span><strong>탐구 주제 찾기</strong></nav><div className="session-bar"><button>이전 세션 (2)⌄</button><button onClick={reset}>＋ 새 세션</button><button className="dark-button">저장</button></div><section className="topic-strip"><span>주제&nbsp; {topic}</span><i>›</i><b>관점 · {selected.name}</b></section><div className="step-content">{step === 1 && <Start student={student} setStudent={setStudent} onNext={generate} loading={loading} error={error} />}{step === 2 && <PerspectiveStep topic={topic} ai={ai} selected={selectedPerspective} setSelected={setSelectedPerspective} onNext={() => setStep(3)} onBack={() => setStep(1)} />}{step === 3 && <PathStep topic={topic} perspective={selected} aiPerspective={selectedAiPerspective} approaches={approaches} sources={ai?.sources} selected={selectedPath} setSelected={setSelectedPath} onNext={() => setStep(4)} onBack={() => setStep(2)} />}{step === 4 && <BasicStep topic={topic} selected={selected} path={approaches[selectedPath]} ai={ai} onNext={() => setStep(5)} onBack={() => setStep(3)} />}{step === 5 && <DeepStep topic={topic} ai={ai} selected={selected} onNext={() => setStep(6)} onBack={() => setStep(4)} />}{step === 6 && <Report report={report} onReset={reset} />}</div></main>;
}

function Start({ student, setStudent, onNext, loading, error }: { student: { number: string; name: string; topic: string }; setStudent: (value: { number: string; name: string; topic: string }) => void; onNext: () => void; loading: boolean; error: string }) { return <section className="start-card"><div className="kicker warm">시작하기</div><h1>학번 · 이름으로 시작</h1><p>관심 주제를 입력하면 Gemini가 2~5페이지의 탐구 흐름을 작성합니다.</p><label>학번<input value={student.number} onChange={(event) => setStudent({ ...student, number: event.target.value })} placeholder="예: 10312" /></label><label>이름<input value={student.name} onChange={(event) => setStudent({ ...student, name: event.target.value })} placeholder="홍길동" /></label><label>관심 주제 또는 개념<textarea value={student.topic} onChange={(event) => setStudent({ ...student, topic: event.target.value })} placeholder="예: 기후 변화, 인공지능의 편향, 학교 일회용품 사용" rows={4} /></label><button className="gradient-button" onClick={onNext} disabled={loading}>{loading ? "Gemini가 탐구 흐름을 작성 중..." : "✦ 시작하기 →"}</button>{error && <><p className="generation-error">{error}</p><button className="continue-button" onClick={() => window.location.reload()}>다시 시도</button></>}</section>; }

function Frame({ title, number, subtitle, children, onNext, onBack, color }: { title: string; number: string; subtitle: string; children: React.ReactNode; onNext: () => void; onBack: () => void; color: string }) { return <section className={`step-frame ${color}`}><div className="kicker">{number}</div><h1>{title}</h1><p className="subtitle">{subtitle}</p>{children}<div className="bottom-actions"><button onClick={onBack}>← 이전</button><button onClick={() => window.location.reload()}>↻ 다시 뽑기</button><button className="next-button" onClick={onNext}>다음 →</button></div></section>; }

function PerspectiveStep({ topic, ai, selected, setSelected, onNext, onBack }: { topic: string; ai: AiContent | null; selected: number; setSelected: (value: number) => void; onNext: () => void; onBack: () => void }) { return <Frame number="관점 - 10가지 사고 형식" title="이 주제를 어떤 관점으로 파고들래요?" subtitle={`'${topic}'에 대해 Gemini가 만든 관점별 질문과 예시입니다. 마음이 끌리는 관점 하나를 골라 보세요.`} onNext={onNext} onBack={onBack} color="violet"><div className="perspective-grid">{perspectives.map((item, index) => { const generated = ai?.perspectives?.find((value) => value.key === item.key); const copy = generated || fallbackCopy(item, topic); return <button key={item.key} className={`perspective-card ${selected === index ? "chosen" : ""}`} onClick={() => setSelected(index)}><span className={`tag ${item.color}`}>관점 · {item.name}</span><strong>{copy.question}</strong><p>{copy.description}</p><small className="example">예시 · {copy.example}</small></button>; })}</div><ResearchSources title="관점 탐구를 위한 참고 자료" sources={ai?.sources} /><details className="more"><summary>＋ 한마디 더보기 (선택)</summary><p>Gemini는 입력 주제를 10가지 사고 형식으로 나누어 서로 다른 탐구 질문을 제안합니다.</p></details></Frame>; }

function PathStep({ topic, perspective, aiPerspective, approaches, sources, selected, setSelected, onNext, onBack }: { topic: string; perspective: Perspective; aiPerspective?: AiContent["perspectives"][number]; approaches: Array<{ title: string; text: string; detail: string }>; sources?: ResearchSource[]; selected: number; setSelected: (value: number) => void; onNext: () => void; onBack: () => void }) { return <Frame number="관점 심화" title="이 관점을 세 단계로 깊게 파고들어요" subtitle={`2페이지에서 선택한 '${perspective.name}' 관점을 ${topic}에 순차적으로 적용해 보세요. 세 형태 중 하나를 선택하면 다음 페이지에 이어집니다.`} onNext={onNext} onBack={onBack} color="green"><div className="selected-lens"><span>2페이지에서 선택한 관점 · {perspective.name}</span><strong>{aiPerspective?.question || `${topic}의 ${perspective.name}은(는) 무엇이며, 어떤 질문으로 확인할 수 있을까?`}</strong></div><div className="path-list">{approaches.map((path, index) => <button key={path.title} className={`path-card ${selected === index ? "chosen" : ""}`} onClick={() => setSelected(index)}><span className="path-number">{index + 1}</span><div><strong>{path.title}</strong><h3>{path.text}</h3><p>{path.detail}</p></div></button>)}</div><ResearchSources title="심화 접근을 위한 참고 자료" sources={sources} /></Frame>; }

function BasicStep({ topic, selected, path, ai, onNext, onBack }: { topic: string; selected: Perspective; path: { title: string; text: string; detail: string }; ai: AiContent | null; onNext: () => void; onBack: () => void }) { const basic = ai?.basic || { what: `${topic}의 핵심 현상은 무엇인가?`, how: `${path.detail} 사례를 하나씩 바꾸며 결과를 비교합니다.`, discover: `${topic}을 설명하는 조건과 예외를 함께 만나게 됩니다.` }; return <Frame number="기본 탐구" title="이 길의 탐구를 한 번에" subtitle="선택한 주제와 경로가 어떤 탐구로 펼쳐지는지 한 번에 보여 드립니다." onNext={onNext} onBack={onBack} color="cyan"><div className="inquiry-cards"><article><span>무엇을 묻나 · {selected.name}</span><strong>{basic.what}</strong></article><article><span>어떻게 알아보나 · {path.title}</span><p>{basic.how}</p></article><article><span>무엇을 만나게 되나</span><p>{basic.discover}</p></article></div><ResearchSources title="탐구 설계를 뒷받침할 자료" sources={ai?.sources} /></Frame>; }

function DeepStep({ topic, ai, selected, onNext, onBack }: { topic: string; ai: AiContent | null; selected: Perspective; onNext: () => void; onBack: () => void }) { const items = ai?.deepening?.length ? ai.deepening : [{ title: "무너지는 방식의 지형도", text: `${topic}이(가) 달라지는 방식은 조건마다 어떻게 다른가?` }, { title: "확장 모형의 최소 조건", text: `${topic}을 더 넓게 설명하려면 어떤 조건을 추가해야 하는가?` }, { title: "예외가 시작되는 순간", text: `${topic}에 대한 일반적인 설명이 어긋나기 시작하는 지점은 어디인가?` }]; return <Frame number="더 깊이 - 1단" title="한 층 더 깊이" subtitle={`${selected.name} 관점에서 ${topic}을 한 단계 더 밀어 보는 질문입니다.`} onNext={onNext} onBack={onBack} color="violet"><div className="deep-list">{items.map((item, index) => <article key={item.title}><span>{index + 1}</span><div><strong>{item.title}</strong><h3>{item.text}</h3><p>자료를 모으고 비교한 뒤, 이 질문에 대한 근거를 자신의 말로 기록합니다.</p></div></article>)}</div><ResearchSources title="심화 탐구를 위한 참고 자료" sources={ai?.sources} /></Frame>; }

function ResearchSources({ title, sources }: { title: string; sources?: ResearchSource[] }) { if (!sources?.length) return null; return <section className="research-sources"><div><span>RESEARCH</span><strong>{title}</strong><small>AI가 정리한 내용은 아래 원문을 열어 직접 확인해 주세요.</small></div><div className="source-list">{sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><em>{source.type}</em><b>{source.title}</b>{source.publisher && <small>{source.publisher}</small>}<i>↗</i></a>)}</div></section>; }

function Report({ report, onReset }: { report: AiContent["report"]; onReset: () => void }) { return <section className="report"><div className="kicker dark">마무리 - 탐구 보고서 목차</div><h1>탐구 목차 · 서론 · 본론 · 결론</h1><p>Gemini가 지금까지의 선택을 탐구 보고서 양식의 목차로 정리했습니다.</p><label>보고서 제목<textarea value={report.title} readOnly rows={2} /></label><h2>I. 서론</h2><article className="report-card"><b>1.1</b><strong>탐구 동기와 배경</strong><textarea defaultValue={report.intro} rows={3} /></article><article className="report-card"><b>1.2</b><strong>탐구 질문 및 목적</strong><textarea defaultValue={report.question} rows={3} /></article><h2>II. 본론</h2><article className="report-card"><b>2.1</b><strong>이론적 배경</strong><textarea defaultValue={report.background} rows={3} /></article><article className="report-card"><b>2.2</b><strong>탐구 방법</strong><textarea defaultValue={report.method} rows={3} /></article><div className="report-actions"><button onClick={onReset}>↻ 새 주제로 다시 시작</button><button className="gradient-button" onClick={() => alert("탐구 세션을 저장했습니다.")}>세션 저장</button></div></section>; }
